# Generated by Django 2.2.7 on 2020-05-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_district_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Population_Info_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('population_density', models.CharField(max_length=200)),
                ('population_rate', models.FloatField()),
                ('households', models.CharField(max_length=200)),
                ('average_person_per_household', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.CreateModel(
            name='Gargage_Deal_Capacity_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('deal_num_total', models.CharField(max_length=200)),
                ('landfill', models.CharField(max_length=200)),
                ('incineration', models.CharField(max_length=200)),
                ('compost', models.CharField(max_length=200)),
                ('else_num', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.CreateModel(
            name='Gargabe_Deal_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('factory_num_total', models.IntegerField()),
                ('landFill', models.IntegerField()),
                ('incineration', models.IntegerField()),
                ('compost', models.IntegerField()),
                ('else_num', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.CreateModel(
            name='Garbage_Info_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('total_garbage', models.CharField(max_length=200)),
                ('collect_transport_garbage', models.CharField(max_length=200)),
                ('volume_of_treated', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.CreateModel(
            name='Garbage_Deal_Volume_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('deal_volume_total', models.CharField(max_length=200)),
                ('landfill', models.CharField(max_length=200)),
                ('incineration', models.CharField(max_length=200)),
                ('compost', models.CharField(max_length=200)),
                ('else_num', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.CreateModel(
            name='Economy_Info_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('gdp', models.CharField(max_length=200)),
                ('gdp_per_capita', models.CharField(max_length=200)),
                ('gdp_growth_rate', models.FloatField()),
                ('unemployment_rate', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='city_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
        ),
    ]
