# Generated by Django 2.2.7 on 2020-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200511_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
        ),
    ]
