# Generated by Django 2.2.7 on 2020-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200511_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy_info_city',
            name='gdp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='economy_info_city',
            name='gdp_growth_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economy_info_city',
            name='gdp_per_capita',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='economy_info_city',
            name='unemployment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='population_info_city',
            name='average_person_per_household',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='population_info_city',
            name='households',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='population_info_city',
            name='population',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='population_info_city',
            name='population_density',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='population_info_city',
            name='population_rate',
            field=models.FloatField(null=True),
        ),
    ]
