# Generated by Django 3.0.7 on 2020-06-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200512_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_median_project',
            fields=[
                ('project_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('basic_size', models.IntegerField()),
                ('ts_size', models.IntegerField()),
                ('rrc_size', models.IntegerField()),
                ('cost_matrix_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_names', models.CharField(max_length=200)),
                ('weight_percentage', models.FloatField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('district', models.CharField(max_length=200)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.p_median_project')),
            ],
        ),
        migrations.CreateModel(
            name='rrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('sub_district', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('max_load', models.IntegerField()),
                ('has_selected', models.IntegerField()),
                ('district_no', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.p_median_project')),
            ],
        ),
        migrations.CreateModel(
            name='cost_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Euclid_distance', models.FloatField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.p_median_project')),
            ],
        ),
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.p_median_project')),
            ],
        ),
    ]
