# Generated by Django 2.2.7 on 2020-07-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200704_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorylist',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='factorylist',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='factorylist',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
