# Generated by Django 2.2.7 on 2020-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200704_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferFactoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='factorylist',
            name='deal',
            field=models.FloatField(default=0),
        ),
    ]
