# Generated by Django 2.2.7 on 2020-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_collectfactorylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl_Data_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(default='08:30:00', max_length=200)),
                ('key_words', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('file_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lstm_project',
            fields=[
                ('project_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('table_size', models.IntegerField()),
                ('project_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PmedianBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='参数名称')),
                ('value', models.FloatField(null=True, verbose_name='参数值')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='单位')),
                ('note', models.CharField(max_length=50, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianCostMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('ts_name', models.CharField(max_length=50, null=True, verbose_name='中转站')),
                ('rrc_name', models.CharField(max_length=50, null=True, verbose_name='集散场')),
                ('cost', models.FloatField(null=True, verbose_name='成本(碳排放)')),
                ('cost_unit', models.CharField(max_length=50, null=True, verbose_name='单位')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianOutputAllocationMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('ts', models.CharField(max_length=50, null=True, verbose_name='集散场')),
                ('rrc', models.CharField(max_length=50, null=True, verbose_name='中转站')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianOutputBuildScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('p_value', models.IntegerField(null=True, verbose_name='p值')),
                ('rrc', models.CharField(max_length=50, null=True, verbose_name='集散场')),
                ('rrc_scale', models.FloatField(null=True, verbose_name='集散场规模')),
                ('scale_unit', models.CharField(max_length=50, null=True, verbose_name='规模单位')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianOutputCostMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('p', models.IntegerField(null=True, verbose_name='p值')),
                ('transport_cost', models.FloatField(null=True, verbose_name='交通成本')),
                ('scale_cost', models.FloatField(null=True, verbose_name='规模成本')),
                ('total_cost', models.FloatField(null=True, verbose_name='总成本')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianRecyclingCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('district', models.CharField(max_length=50, null=True, verbose_name='区')),
                ('sub_district', models.CharField(max_length=50, null=True, verbose_name='街镇')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='位置')),
                ('lng', models.FloatField(null=True, verbose_name='经度')),
                ('lat', models.FloatField(null=True, verbose_name='纬度')),
                ('max_load', models.FloatField(null=True, verbose_name='处理量')),
                ('max_load_unit', models.CharField(max_length=50, null=True, verbose_name='单位')),
                ('has_selected', models.BooleanField(default=0, null=True, verbose_name='已选择')),
            ],
        ),
        migrations.CreateModel(
            name='PmedianTransferStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('project_id', models.CharField(max_length=50, null=True, verbose_name='项目编号')),
                ('sub_names', models.CharField(max_length=50, null=True, verbose_name='所属街镇')),
                ('weight_percentage', models.FloatField(null=True, verbose_name='产量权重因子')),
                ('lng', models.FloatField(null=True, verbose_name='经度')),
                ('lat', models.FloatField(null=True, verbose_name='维度')),
                ('district', models.CharField(max_length=50, null=True, verbose_name='所属区')),
            ],
        ),
    ]
