# Generated by Django 2.2.7 on 2020-08-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_crawl_data_record_lstm_project_pmedianbasic_pmediancostmatrix_pmedianoutputallocationmatrix_pmediano'),
    ]

    operations = [
        migrations.AddField(
            model_name='lstm_project',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
