# Generated by Django 2.2.7 on 2020-08-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_lstm_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='lstm_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('population', models.FloatField(max_length=255)),
                ('population_density', models.FloatField(max_length=255)),
                ('total_households', models.FloatField(max_length=255)),
                ('average_person_per_household', models.FloatField(max_length=255)),
                ('gdp', models.FloatField(max_length=255)),
                ('per_capita_gdp', models.FloatField(max_length=255)),
                ('status', models.IntegerField(default=0, max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lstm_project')),
            ],
        ),
    ]
