# Generated by Django 2.2.7 on 2020-08-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_lstm_project_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstm_project',
            name='status',
            field=models.CharField(default='未运行', max_length=255),
        ),
    ]
