# Generated by Django 2.2.7 on 2020-09-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200901_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='average_population_per_household',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='consumer_expenditure',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='general_public_expenditure',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='greening_coverage',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='gross_domestic_product_of_the_first_industry',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='gross_domestic_product_per_capita',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='gross_local_product',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='gross_value_of_secondary_industry',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='gross_value_of_the_tertiary_industry',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='investment_in_environmental_protection',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='investment_in_urban_infrastructure',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='level_of_education',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='municial_household_garbage',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='number_of_college_students',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='number_of_households',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='population_of_density',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='resident_population',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='urban_population_density',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='multi_regression_parameter',
            name='urban_residents_per_capita_disposable_income',
            field=models.FloatField(default=None),
        ),
    ]
