# Generated by Django 2.2.7 on 2020-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_kmeans_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
