# Generated by Django 2.2.7 on 2020-09-10 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_algorithm_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm_project',
            fields=[
                ('project_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='algorithm_table',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.algorithm_project'),
        ),
    ]
