# Generated by Django 2.2.7 on 2020-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20200910_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm_table',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='algorithm_table',
            name='pic_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
