# Generated by Django 2.2.7 on 2020-09-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200910_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm_table',
            name='project_id',
        ),
        migrations.AddField(
            model_name='p_median_project',
            name='project_state',
            field=models.CharField(default='未运行', max_length=200),
        ),
        migrations.AddField(
            model_name='pmedianoutputallocationmatrix',
            name='p_value',
            field=models.IntegerField(null=True, verbose_name='p值'),
        ),
        migrations.DeleteModel(
            name='algorithm_project',
        ),
        migrations.DeleteModel(
            name='algorithm_table',
        ),
    ]
