# Generated by Django 2.2.7 on 2020-09-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20200911_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm_project',
            fields=[
                ('project_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=0)),
                ('describe', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='algorithm_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pic_url', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('project_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.algorithm_project')),
            ],
        ),
    ]
