# Generated by Django 2.2.7 on 2020-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_algorithm_project_algorithm_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation_project',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='未运行', max_length=255)),
            ],
        ),
    ]
