# Generated by Django 2.2.7 on 2020-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_relation_hot_matrix_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_parameter',
            name='year',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
