# Generated by Django 2.2.7 on 2020-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20200921_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation_parameter',
            old_name='people_per_household',
            new_name='people_per_capita',
        ),
        migrations.AlterField(
            model_name='relation_hot_matrix_result',
            name='year',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
