# Generated by Django 2.2.7 on 2020-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20200924_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='garbage_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('cook', models.FloatField()),
                ('paper', models.FloatField()),
                ('plastic', models.FloatField()),
                ('timber', models.FloatField()),
                ('clothe', models.FloatField()),
                ('wood', models.FloatField()),
                ('ash', models.FloatField()),
                ('clay', models.FloatField()),
                ('glass', models.FloatField()),
                ('metal', models.FloatField()),
                ('other', models.FloatField()),
                ('mix', models.FloatField()),
                ('recycle', models.FloatField()),
                ('fire', models.FloatField()),
            ],
        ),
    ]
