# Generated by Django 2.2.7 on 2020-09-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_garbage_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage_element',
            name='city_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
            preserve_default=False,
        ),
    ]
