# Generated by Django 2.2.7 on 2020-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_algorithm_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pic_url', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='algorithm_table',
        ),
    ]
