# Generated by Django 2.2.7 on 2020-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_selected_algorithm_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='resource/img', verbose_name='图片')),
            ],
        ),
    ]
