# Generated by Django 2.2.7 on 2020-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='webfront/src/views/image', verbose_name='图片'),
        ),
    ]
