# Generated by Django 2.2.7 on 2020-10-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20201019_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='webfront/dist/static/img', verbose_name='图片'),
        ),
    ]
