# Generated by Django 2.2.7 on 2020-10-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20201019_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kmeans_parameter',
        ),
    ]
