# Generated by Django 3.1.2 on 2020-10-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20201019_1121'),
        ('backend', '0051_auto_20201014_1712'),
    ]

    operations = [
    ]
