# Generated by Django 2.2.7 on 2020-10-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_merge_20201023_1426'),
        ('backend', '0064_kmeans_result_district'),
    ]

    operations = [
    ]
