# Generated by Django 2.0 on 2020-10-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_kmeans_result_district'),
        ('backend', '0060_merge_20201023_1426'),
    ]

    operations = [
    ]
