# Generated by Django 2.2.7 on 2020-10-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_merge_20201024_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_algorithm_table',
            name='algorithm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.algorithm_project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
