# Generated by Django 2.2.7 on 2020-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_auto_20201024_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/file/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
    ]
