# Generated by Django 2.2.7 on 2020-10-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_table',
            name='sort_Id',
            field=models.IntegerField(default=0),
        ),
    ]
