# Generated by Django 2.2.7 on 2020-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_model_table_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_algorithm_table',
            name='status',
            field=models.CharField(default='未运行', max_length=100),
        ),
    ]
