# Generated by Django 2.2.7 on 2020-11-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_selected_algorithm_table_status'),
        ('backend', '0065_merge_20201026_1344'),
    ]

    operations = [
    ]
