# Generated by Django 2.2.7 on 2020-11-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20201104_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage_info_city',
            name='total_garbage',
        ),
    ]
