# Generated by Django 2.2.7 on 2020-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_remove_garbage_info_city_total_garbage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gargabe_deal_city',
            name='collect_factory_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gargabe_deal_city',
            name='compost',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gargabe_deal_city',
            name='else_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gargabe_deal_city',
            name='factory_num_total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gargabe_deal_city',
            name='incineration',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gargabe_deal_city',
            name='landFill',
            field=models.IntegerField(default=None),
        ),
    ]
