# Generated by Django 2.2.7 on 2020-11-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_auto_20201104_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gargage_deal_capacity_city',
            name='compost',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gargage_deal_capacity_city',
            name='deal_num_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gargage_deal_capacity_city',
            name='else_num',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gargage_deal_capacity_city',
            name='incineration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gargage_deal_capacity_city',
            name='landfill',
            field=models.CharField(default='', max_length=200),
        ),
    ]
