# Generated by Django 2.2.7 on 2020-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_auto_20201105_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage_deal_volume_city',
            name='compost',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_deal_volume_city',
            name='deal_volume_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_deal_volume_city',
            name='else_num',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_deal_volume_city',
            name='incineration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_deal_volume_city',
            name='landfill',
            field=models.CharField(default='', max_length=200),
        ),
    ]
