# Generated by Django 2.2.7 on 2020-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_dangerous_garbage_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage_element',
            name='fire',
        ),
        migrations.RemoveField(
            model_name='garbage_element',
            name='mix',
        ),
        migrations.RemoveField(
            model_name='garbage_element',
            name='recycle',
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='ash',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='china',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='clothe',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='cook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='glass',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='metal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='other',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='paper',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='plastic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='garbage_element',
            name='wood',
            field=models.CharField(default='', max_length=200),
        ),
    ]
