# Generated by Django 2.2.7 on 2020-11-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_garbage_clear_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageIron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=255)),
                ('produce', models.CharField(default='', max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City')),
            ],
        ),
    ]
