# Generated by Django 2.2.7 on 2020-11-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_garbage_info_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy_Info_District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('gdp', models.CharField(default='', max_length=255)),
                ('gdp_first_industry', models.CharField(default='', max_length=255)),
                ('gdp_second_industry', models.CharField(default='', max_length=255)),
                ('gdp_third_industry', models.CharField(default='', max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.District')),
            ],
        ),
    ]
