# Generated by Django 2.2.7 on 2020-11-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_economy_info_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population_Info_District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('population', models.CharField(max_length=255)),
                ('population_density', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.District')),
            ],
        ),
    ]
