# Generated by Django 2.2.7 on 2020-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_pearsonresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='', max_length=200)),
                ('sort', models.IntegerField(default=1)),
                ('formula', models.CharField(default='', max_length=255)),
                ('r_square', models.CharField(default='', max_length=255)),
                ('mse', models.CharField(default='', max_length=255)),
                ('rmse', models.CharField(default='', max_length=255)),
                ('sse', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
