# Generated by Django 2.2.7 on 2020-12-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_testreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testreport',
            old_name='sse',
            new_name='mae',
        ),
    ]
