# Generated by Django 2.2.7 on 2020-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_testreport_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='choose_col',
            field=models.CharField(default='', max_length=255),
        ),
    ]
