# Generated by Django 2.2.7 on 2020-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_garbage_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='choose_col',
            field=models.TextField(default=''),
        ),
    ]
