# Generated by Django 2.2.7 on 2020-12-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_auto_20201215_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='formula',
            field=models.TextField(default='', max_length=255),
        ),
    ]
