# Generated by Django 2.2.7 on 2020-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_auto_20201215_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='formula',
            field=models.TextField(default=''),
        ),
    ]
