# Generated by Django 2.2.7 on 2020-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_auto_20201215_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/modelfile/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
    ]
