# Generated by Django 2.2.7 on 2020-12-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20201222_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lstm_parameter',
        ),
    ]
