# Generated by Django 2.2.7 on 2020-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_delete_lstm_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLinearRegressionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/modelfile/linearregression/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
    ]
