# Generated by Django 2.2.7 on 2020-12-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_modellinearregressionfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinearRegressionParameter',
        ),
    ]
