# Generated by Django 2.2.7 on 2020-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_delete_linearregressionparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegressionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/modelfile/regression/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
    ]
