# Generated by Django 2.2.7 on 2020-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_modelregressionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelKmeansFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/modelfile/kmeans/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
        migrations.DeleteModel(
            name='multi_regression_parameter',
        ),
    ]
