# Generated by Django 2.2.7 on 2020-12-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_auto_20201228_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kmeans_parameter',
        ),
    ]
