# Generated by Django 2.2.7 on 2020-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_delete_kmeans_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRelationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/modelfile/relation/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
        migrations.DeleteModel(
            name='relation_parameter',
        ),
    ]
