# Generated by Django 3.1.5 on 2021-01-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_auto_20201229_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='static/testfile/%Y/%m/%d', verbose_name='文件')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
